version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"  # Set your AWS region here
    AWS_ACCOUNT_ID: "009160041388"   # Set your AWS account ID here
    PLATFORM_IMAGE_NAME: "quant-container-store"
    PLATFORM_TAG: "latest"
    GATEWAY_IMAGE_NAME: "ibkr-gateway"
    GATEWAY_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "$(ls)"
      - export DOCKER_BUILDKIT=1
      - export BUILDKIT_PROGRESS=plain
      - export PROGRESS_NO_TRUNC=1
      - echo "$(ls)"
      - docker build -t $PLATFORM_IMAGE_NAME:$PLATFORM_TAG --progress=plain .
      - docker tag $PLATFORM_IMAGE_NAME:$PLATFORM_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PLATFORM_IMAGE_NAME:$PLATFORM_TAG
      - docker compose build
      - docker tag $GATEWAY_IMAGE_NAME:$GATEWAY_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$GATEWAY_IMAGE_NAME:$GATEWAY_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PLATFORM_IMAGE_NAME:$PLATFORM_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$GATEWAY_IMAGE_NAME:$GATEWAY_TAG